models/Prospectos.php
<?php

namespace app\models;
use app\models\entities\EntityProspectos;
use app\models\Prospectos;
use app\models\Cliente;
use yii\db\ActiveRecord;

class Prospectos extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface
{

    public static function tableName()
    {
        return EntityProspectos::tableName();
    }

    public function rules()
    {
            return [
                [['email','rfc','numeroTelefono','nombre','apellidoPaterno', 'apellidoMaterno','pais'], 'required'],
                [['ciudad'],'required', 'message' => 'La Ciudad no debe estar vacía.'],
                [['fechaNacimiento'],'required', 'message' => 'La Fecha de Nacimiento no debe estar vacía.'],
                [['email'], 'unique','targetClass'=>'\app\models\Prospectos','message' => 'Usuario ya registrado.'],
                [['numeroTelefono','email','nombre','apellidoPaterno', 'apellidoMaterno','pais','ciudad'],'string','max' => 30, 'message' => 'El campo excede los 30 caracteres.'],
                [['rfc'],'string','max' => 13, 'message' => 'El campo excede los 13 caracteres.']
            ];
    }


    public function attributeLabels(){
        return[ 
            'id' => 'ID',
            'nombre' => 'Nombre',
            'email' => 'Correo electrónico',
            'apellidoPaterno' => 'Apellido paterno',
            'apellidoMaterno' => 'Apellido materno',
            'pais' => 'Pais',
            'ciudad' => 'Ciudad',
            'numeroTelefono' => 'Teléfono',
            'fechaNacimiento' => 'Fecha de Nacimiento'
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }

    public static function obtenerEnEspera()
    {
        return static::find()->where(['estatus'=>'ESPERA'])->all();
    }

    public static function obtenerClientesBuscador($search){
        return static::find()->where(['LIKE','nombre',$search])->orWhere(['LIKE','apellidoPaterno',[$search]])->orWhere(['LIKE','apellidoMaterno',[$search]])->orWhere(['LIKE','numeroTelefono',[$search]])->orWhere(['LIKE','email',[$search]])->orWhere(['LIKE','pais',[$search]])->orWhere(['LIKE','ciudad',[$search]])->all();
    }

    public static function actualizar($prospecto){
        $prospecto->estatus='ACEPTADO';
        $prospecto->update();
    }
    public static function rechazar($id){
        $prospect=Prospectos::findOne($id);
        $prospect->estatus='RECHAZADO';
        return $prospect->update();
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    public function setPassword($password)
    {
        $this->password = \Yii::$app->security->generatePasswordHash($password);
    }

    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    }

    public function generateAuthKey(){
        $this->authKey = \Yii::$app->security->generateRandomString();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    public function validatePassword($password)
    {
        return \Yii::$app->security->validatePassword($password,$this->password);
    }
}

controllers/ProspectoController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use app\models\Prospectos;
use app\models\FormSearch;
use yii\helpers\Html;
use app\models\Cliente;

class ProspectoController extends Controller
{
    public function actionRequest(){

    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionDelete(){
        if(Yii::$app->request->post()){
            $msg=null;
            $tipo=0;
            $id = Html::encode($_POST["id"]);
            if((int)$id){
                $form = new FormSearch;
                $search = null;
                if(Prospectos::rechazar($id) !==false){
                    $model = Prospectos::obtenerEnEspera();
                    $msg="Prospecto borrado correctamente";
                    $tipo=1;
                    return $this->render('aceptacion',['model'=>$model,'form'=>$form,'msg'=>$msg,'tipo'=>$tipo,'search'=>$search]);
                }else{
                    $model = Prospectos::obtenerEnEspera();
                    $msg="Prospecto no pudo ser borrado";
                    return $this->render('aceptacion',['model'=>$model,'form'=>$form,'msg'=>$msg,'tipo'=>$tipo,'search'=>$search]);
                }
            }else{
                $form = new FormSearch;
                $search = null;
                $model = Prospectos::obtenerEnEspera();
                $msg="Prospecto no pudo ser borrado";
                return $this->render('aceptacion',['model'=>$model,'form'=>$form,'msg'=>$msg,'tipo'=>$tipo,'search'=>$search]);
            }
        }
    }
    public function actionAceptar(){
        $msg=null;
        $tipo=0;
        if(Yii::$app->request->get("id")){
              $idProspect = Html::encode($_GET["id"]);
              if((int)$idProspect){
                $prospecto = Prospectos::findOne($idProspect);
                $user = new User();          
                $user = User::guardarUserNuevo($prospecto);
                $cliente=Cliente::guardarNuevoCliente($prospecto,$user->id);             
                Prospectos::actualizar($prospecto);
                $form = new FormSearch;
                $contact = new ContactForm();
                ContactForm::contactProspect(Yii::$app->params['adminEmail'],$user->email, $cliente->nombre);
                $model = Prospectos::obtenerEnEspera();
                $search = null;
                $msg="Prospecto fue aceptado ";
                return $this->render('aceptacion',['model'=>$model,'form'=>$form,'msg'=>$msg,'tipo'=>1,'search'=>$search]);
            }
        }else{
            $form = new FormSearch;
            $search = null;
            $model = Prospectos::find()->obtenerEnEspera();
            $msg="";
            return $this->render('aceptacion',['model'=>$model,'form'=>$form,'msg'=>$msg,'tipo'=>$tipo,'search'=>$search]);
        }      
    }

    public function actionRegister(){
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new Prospectos();
        if ($model->load(Yii::$app->request->post())){
            if($model->validate()){
                $model->save(false);
                Yii::$app->session->setFlash('success','Has sido registrado como prospecto, espere un correo de aceptación.');
                return $this->redirect(['site/login']);
            }
        }
        return $this->render('signup',[
            'model' => $model,
        ]);

    }


    public function actionAceptacion()
    {
        $model= Prospectos::obtenerEnEspera();
        $msg=null;
        $tipo=3;
        $form = new FormSearch;
        $search = null;
        if($form->load(Yii::$app->request->get())){
            if($form->validate()){
                $search = Html::encode($form->q);
                $model = Prospectos::obtenerClientesBuscador($search);   
            }
        }
        return $this->render('aceptacion',['model'=>$model,'form'=>$form,'msg'=>$msg,'tipo'=>$tipo,'search'=>$search]);
    }
}

views/prospecto/aceptacion.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Prospectos';
$this->params['breadcrumbs'][] = $this->title;
?> 
<h1>Lista de Prospectos de Usuario</h1>

<?php $f = ActiveForm::begin([
    "method" => "get",
    "action"=> Url::toRoute("prospecto/aceptacion"),
    'enableClientValidation' => true,
    ]);

?>
<div class = "form-group">
  <?= $f->field($form,"q")->input("search") ?>
</div>
<?= Html::submitButton("Buscar",["class"=>"btn btn-primary"]) ?>
<?php $f->end() ?>

<h3> <?= $search ?> </h3>

<?php if($tipo==1): ?>
    <div class="alert alert-success">
    <h4 ><?= $msg ?></h4>
        </div>
        <?php endif; ?>
<?php if($tipo==0): ?>
    <div class="alert alert-danger">
        <?= nl2br(Html::encode($msg)) ?>
    </div>
    <?php endif; ?>
<table class="table table-bordered">
    <tr>
        <th>Nombre Completo</th>
        <th>Telefono</th>
        <th>Email</th>
        <th>Pais</th>
        <th>Ciudad</th>
        <th></th>
        <th></th>
    </tr>
    <?php foreach($model as $row): ?>
    <tr>
        <td><?= $row->nombre  ?><?= " "?><?= $row->apellidoPaterno  ?><?= " "?><?= $row->apellidoMaterno  ?></td>
        <td><?= $row->numeroTelefono ?> </td>
        <td><?= $row->email ?></td>
        <td><?= $row->pais ?></td>
        <td><?= $row->ciudad ?></td>
        <td><a href="<?= Url::toRoute(["prospecto/aceptar", "id" => $row->id]) ?>" class="btn btn-success">Aceptar</a></td>
        <td>
            <a href="#" data-toggle="modal" data-target="#id_username_<?= $row->id ?>" class="btn btn-danger">Eliminar</a>
            <div class="modal fade" role="dialog" aria-hidden="true" id="id_username_<?= $row->id ?>">
                      <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                    <h4 class="modal-title">Eliminar Prospecto</h4>
                              </div>
                              <div class="modal-body">
                                    <p>¿Realmente deseas eliminar al prospecto <?= $row->nombre ?>?</p>
                              </div>
                              <div class="modal-footer">
                              <?= Html::beginForm(Url::toRoute("prospecto/delete"), "POST") ?>
                                    <input type="hidden" name="id" value="<?= $row->id ?>">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                    <button type="submit" class="btn btn-primary">Eliminar</button>
                              <?= Html::endForm() ?>
                              </div>
                            </div>
                      </div>
            </div>
        </td>
    </tr>
    <?php endforeach ?>
</table>

views/prospecto/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Registrarse';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="prospecto-register">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Por favor ingrese los datos que se piden a continuación:</p>
    
    <div class="row">
        <div class="col-lg-5">
        <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

        <?= $form->field($model, 'nombre')->textInput() ?>
        <?= $form->field($model, 'apellidoPaterno')->textInput() ?>
        <?= $form->field($model, 'apellidoMaterno')->textInput() ?>

        <?= $form->field($model, 'pais')->textInput() ?>

        <?= $form->field($model, 'ciudad')->textInput() ?>

        <?= $form->field($model, 'numeroTelefono')->textInput() ?>
        <?= $form->field($model, 'fechaNacimiento')->input('date',['value'=>'1990-02-02']) ?>
    

        <?= $form->field($model, 'rfc')->textInput() ?>

        <?= $form->field($model, 'email')->input('email') ?>

        <div class="form-group">
            <?= Html::submitButton('Registrarse', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
        </div>

        <?php ActiveForm::end(); ?>

        </div>
    </div>

</div>