models/Venta.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use app\models\entities\EntityVenta;

class Venta extends \yii\db\ActiveRecord{

    public static function tableName()
    {
        return EntityVenta::tableName();
    }

    public function attributeLabels(){
        return[ 
            'idTipoPago' => 'Tipo de pago',
        ];
    }

    public function setFolio($folio)
    {
        $this->folio = $folio;
    }

    public function setTotal($total)
    {
        $this->total = $total;
    }

    public function setSubtotal($subtotal)
    {
        $this->subtotal = $subtotal;
    }

    public function setIva($iva)
    {
        $this->iva = $iva;
    }

    public function setIdUsuario($idUsuario)
    {
        $this->idUsuario = $idUsuario;
    }

    public function setIdDireccion($idDireccion)
    {
        $this->idDireccion = $idDireccion;
    }

    public function setIdTipoPago($idTipoPago)
    {
        $this->idTipoPago = $idTipoPago;
    }

    public function setFechaVenta($fechaVenta)
    {
        $this->fechaVenta = $fechaVenta;
    }

    public function setStatus($status)
    {
        $this->status = $status;
    }

    public static function obtenerVentaPorFolio($folio)
    {
        return static::findOne(['folio' => $folio]);
    }

    public static function obtenerFolio()
    {
        $result = \Yii::$app->db->createCommand("CALL aumentar_folio('ventas', @folio);") 
                      ->execute();
        return \Yii::$app->db->createCommand("select @folio;")->queryScalar();
    }

    public function cambiarTotalSubtotal($total){
        $venta = new Venta();
        $venta->setTotal($total);
        $venta->setSubtotal($total * 0.84);
        $venta->setIva($total * 0.16);
        return $venta;
    }
    public function guardarVenta($total, $idUsuario, $idDireccion, $idTipoPago){
        $venta = new Venta();
        date_default_timezone_set('America/Mazatlan');
        $fechaActual = date("Y-m-d");
        $status = ($idTipoPago == 1) ? 'SALDADA' : 'NO SALDADA';
        $venta->setFolio(static::obtenerFolio());
        $venta->setTotal($total);
        $venta->setSubtotal($total * 0.84);
        $venta->setIva($total * 0.16);
        $venta->setIdUsuario($idUsuario);
        $venta->setIdDireccion($idDireccion);
        $venta->setIdTipoPago($idTipoPago);
        $venta->setFechaVenta($fechaActual);
        $venta->setStatus($status);
        $venta->save();
        return $venta;
    }

}

controllers/VentasController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\Response;
use app\models\Prenda;
use app\models\Carrito;
use app\models\Direccion;
use app\models\Pago;
use app\models\Venta;
use app\models\VentaDetalle;
use app\models\Email;
use app\models\FechaEntrega;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use app\models\Componente;
use app\models\Categoria;
use app\models\Temporada;
use app\models\SubCategoria;
use app\models\PrendaPersonalizada;


class VentasController extends Controller
{
    public function actionCarrito(){
        $idUsuario = Yii::$app->session['idUsuario'];
        $carrito = Carrito::obtenerCarritoPorUsuario($idUsuario);
        $prendas = Carrito::obtenerPrendasPorUsuario($idUsuario);
        $total = Carrito::totalCarrito($idUsuario);
        $urlbase = Url::base(true);
        $fechaEntrega = FechaEntrega::obtenerFechaEntrega($idUsuario);
        return $this->render('carrito',[
            'carrito' => $carrito,
            'prendas' => $prendas,
            'total' => $total,
            'fechaEntrega' => $fechaEntrega,
            'urlbase' => $urlbase
        ]);
    }

    public function actionProceder(){
        $direccion = new Direccion();
        $idUsuario = Yii::$app->session['idUsuario'];
        $direcciones = Direccion::obtenerDireccionesPorUsuario($idUsuario);
        return $this->render('direccion',[
            'model' => $direccion,
            'direcciones' => $direcciones
        ]);
    }

    public function actionAgregardireccion(){
        $direccion = new Direccion();
        if ($direccion->load(Yii::$app->request->post())){
            if($direccion->validate()){
                $direccion= Direccion::guardarDireccion($direccion,Yii::$app->session['idUsuario']);
                Yii::$app->session['idDireccion'] = $direccion->id;
                Yii::$app->session->setFlash('success','Direción de envío agregada con éxito al pedido.');             
                $total = Carrito::totalCarrito(Yii::$app->session['idUsuario']);
                $venta = Venta::cambiarTotalSubtotal($total);
                return $this->render('pago',[
                    'model' => $venta
                ]);
            }
        }
        Yii::$app->session->setFlash('error','Ha ocurrido un error al guardar dirección');
        $idUsuario = Yii::$app->session['idUsuario'];
        $direcciones = Direccion::obtenerDireccionesPorUsuario($idUsuario);
        return $this->render('direccion',[
            'model' => $direccion,
            'direcciones' => $direcciones
        ]);
    }
    public function actionUsardireccion(){
        $idDireccion = Html::encode($_POST["id"]);
        Yii::$app->session['idDireccion']=$idDireccion;
        Yii::$app->session->setFlash('success','Direción de envío agregada con éxito.');             
        $total = Carrito::totalCarrito(Yii::$app->session['idUsuario']);
        $venta= Venta::cambiarTotalSubtotal($total);
        return $this->render('pago',[
            'model' => $venta
        ]);
    }

    public function actionAgregarpago(){
        ini_set('max_execution_time', 300);
        $venta = new Venta();

        if ($venta->load(Yii::$app->request->post())){
            $idTipoPago = (int) Yii::$app->request->post()['Venta']['idTipoPago'];
            $idDireccion = Yii::$app->session['idDireccion'];
            $idUsuario = Yii::$app->session['idUsuario'];
            $total = Carrito::totalCarrito($idUsuario);
            $venta = Venta::guardarVenta($total, $idUsuario, $idDireccion, $idTipoPago);

            $carrito = Carrito::obtenerCarritoPorUsuario($idUsuario);
            $prendasCarrito = Carrito::obtenerPrendasPorUsuario($idUsuario);
            VentaDetalle::guardarVentasDetalle($carrito, $prendasCarrito, $venta->folio);

            Pago::guardarPago($idTipoPago, $venta->folio, $total);

            $fechaEntrega = FechaEntrega::obtenerFechaEntrega($idUsuario);
            Email::enviarCorreoConfirmacion($prendasCarrito, $carrito, $total, $fechaEntrega);

            Carrito::limpiarCarritoPorIdUsuario($idUsuario);
            Yii::$app->session->setFlash('success','El pago se realizó con exito. Un correo de confirmación fue enviado a su correo.');
            
            $prendasTemporada = Prenda::obtenerPrendasPorTemporadas();
            $prendas = Prenda::obtenerPrendasSite();
            
            return $this->render('//site/index',[
                'model' => $venta,
                'prendas'=>$prendas,
                'prendasTemporada'=> $prendasTemporada,
                'model' => $venta
            ]);

        }
        Yii::$app->session->setFlash('error','Ha ocurrido un error al procesar el pago.');
        return $this->render('pago',[
            'model' => $venta
        ]);

    }

    public function actionAgregarcarrito(){
        
        if (Yii::$app->request->post()){
                $idUsuario = Yii::$app->session['idUsuario'];
                $idPrenda = $_POST['idprenda'];
                $talla = $_POST['talla'];
                $color = $_POST['color'];
                $cantidad = $_POST['cantidad'];

                if(Yii::$app->session['idUsuario'] != null){
                    $existeElemento = Carrito::obtenerUsuarioPrenda($idUsuario,$idPrenda);

                    if(isset($_POST['idcomponente'])){
                        $ids = explode("|", $_POST['idcomponente']);
                        $precio = Componente::obtenerSumaPrecio($ids);
                        $prendaNueva =Prenda::guardarPrendaPersonalizada($idPrenda,$precio);
                        $idPrendaPersonalizada = $prendaNueva->id;
                        PrendaPersonalizada::guardarPrendasPersonalizadas($idUsuario,$idPrenda,$ids);
                        Carrito::guardarNuevaLineaVenta($idPrendaPersonalizada,$idUsuario,$cantidad,$talla,$color);
                        $mensaje = 'Artículo personalizado agregado al carrito.';
                        $tipoMensaje = 1;
                        $model = Prenda::findOne($idPrenda);
                    }else{

                        if($existeElemento==null){
                            Carrito::guardarNuevaLineaVentaBasica($idPrenda,$idUsuario,$cantidad,$talla,$color);
                            $mensaje = 'Artículo agregado al carrito.';
                            $tipoMensaje = 1;
                        }else{
                            if($existeElemento->color==$color && $existeElemento->talla==$talla){
                                Carrito::actualizarLineaVenta($existeElemento,$cantidad);
                                $mensaje = 'Artículo agregado al carrito.';
                                $tipoMensaje = 1;
                            }else{
                                Carrito::guardarNuevaLineaVentaBasica($idPrenda,$idUsuario,$cantidad,$talla,$color);
                                $mensaje = 'Artículo agregado al carrito.';
                                $tipoMensaje = 1;
                            }
                        }

                    }
       
                }else{
                    $mensaje = 'Necesita autenticarse para agregar al carrito.';
                    $tipoMensaje = 0;
                    
                }
                $model = Prenda::findOne($idPrenda);
                Yii::$app->session['idPrenda'] = $idPrenda;
                $componentes = Componente::obtenerComponentesPrenda($idPrenda);
                $descripciontemporada= Temporada::findOne($model->idTemporada)->tipoTemporada;
                $descripcionCategoria = Categoria::findOne($model->idCategoria)->descripcion;
                $descripcionSubCategoria = SubCategoria::findOne($model->idSubCategoria)->descripcion;
                return $this->render('//prendas/prendaPersonalizar',['msg'=>$mensaje,
                                                                        'model'=>$model,
                                                                        'temporada'=>$descripciontemporada,
                                                                        'categoria'=>$descripcionCategoria,
                                                                        'subcategoria'=>$descripcionSubCategoria,
                                                                        'componentes'=>$componentes, 
                                                                        'tipo'=>$tipoMensaje]);
        }
    }

    public function actionBorrarcarrito(){
        if (Yii::$app->request->post()){
            $idPrenda = Html::encode($_POST["id"]);
            $idUsuario = Yii::$app->session['idUsuario'];

            Carrito::borrarElemento($idUsuario, $idPrenda);

            $carrito = Carrito::obtenerCarritoPorUsuario($idUsuario);
            $prendas = Carrito::obtenerPrendasPorUsuario($idUsuario);
            $total = Carrito::totalCarrito($idUsuario);
            $urlbase = Url::base(true);
            $fechaEntrega = FechaEntrega::obtenerFechaEntrega($idUsuario);
            return $this->render('carrito',[
                'carrito' => $carrito,
                'prendas' => $prendas,
                'total' => $total,
                'fechaEntrega' => $fechaEntrega,
                'urlbase' => $urlbase
            ]);
        }
    }
}

views/ventas/carrito.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

$this->title = 'Carrito';
$this->params['breadcrumbs'][] = $this->title;
?> 

<h1 class="titulo">Carrito de compra</h1>

<?php if(count($prendas) > 0) { ?>

    <div class="divagregar">
        <?= Html::beginForm(Url::toRoute("ventas/proceder"), "POST") ?>
            <button type="submit" class="btn btn-primary">Proceder Compra</button>
        <?= Html::endForm() ?>
    </div>

    <h3> Fecha de entrega aproximada: <?=$fechaEntrega ?></h3>
    <table class="table table-bordered table-striped table-hover text-center">
        <thead>
        <tr>
            <th class="tableCell baseWidth">Imagen</th>
            <th class="tableCell baseWidth">Nombre</th>
            <th class="tableCell baseWidth">Tipo de Prenda</th>
            <th class="tableCell baseWidth">Cantidad</th>
            <th class="tableCell baseWidth">Talla</th>
            <th class="tableCell baseWidth">Color</th>
            <th class="tableCell baseWidth">Precio Unitario</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php 
            foreach($prendas as $prenda):
                $urlfinal = $urlbase.$prenda->urlImagen;
        ?>
                <tr> 
                    <td class="tableCell"><img src=<?=$urlfinal ?> alt="Imagen de la Prenda" style="width:75px;height:75px;" ></td>
                    <td class="tableCell"><?= $prenda->nombre  ?></td>
                    <td class="tableCell"><?= $prenda->tipoPrenda ?> </td>
                    <td class="tableCell"><?= $carrito[$prenda->id]->cantidad ?> </td>
                    <td class="tableCell"><?= $carrito[$prenda->id]->talla ?> </td>
                    <td class="tableCell"><?= $carrito[$prenda->id]->color ?> </td>
                    <td class="tableCell">$<?= $prenda->precio ?></td>
                    <td class="tableCell">
                    <a href="#" data-toggle="modal" data-target="#id_username_<?= $prenda->id ?>" class="btn btn-danger">Eliminar</a>
                    <div class="modal fade" role="dialog" aria-hidden="true" id="id_username_<?= $prenda->id ?>">
                            <div class="modal-dialog">
                                    <div class="modal-content">
                                    <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                            <h4 class="modal-title">Eliminar Prenda</h4>
                                    </div>
                                    <div class="modal-body">
                                            <p>¿Realmente deseas eliminar del carrito la prenda <?= $prenda->nombre ?>?</p>
                                    </div>
                                    <div class="modal-footer">
                                    <?= Html::beginForm(Url::toRoute("ventas/borrarcarrito"), "POST") ?>
                                    <input type="hidden" name="id" value="<?= $prenda->id ?>">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                    <button type="submit" class="btn btn-primary">Eliminar</button>
                                    <?= Html::endForm() ?>
                                    </div>
                                    </div>
                            </div>
                    </div>
                </td>
                </tr>
        <?php 
            endforeach 
        ?>
            <tr> 
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>Total: </td>
                <td>$<?= number_format($total,2,".",",") ?> </td>
                <td></td>
            </tr>
        </tbody>
    </table>

<?php } else { ?>
    <img class="empty-cart" src="/images/empty-cart.jpg" alt="">
    <h3 class="text-center">Por el momento no cuenta con prendas en su carrito.</h3>
    <h4 class="text-center">Navega por nuestra página y agrega las prendas que mas te gusten.</h4>
<?php } ?>

views/ventas/direccion.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Dirección';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="direccion-register">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Por favor ingrese los datos que se piden a continuación:</p>
    
    <div>
        <div>
            <?php $form = ActiveForm::begin([
                                    'id' => 'form-direccion',
                                    'method' => 'post',
                                    'action' => ['ventas/agregardireccion'],
                                ]); ?>

                <?= $form->field($model, 'calle')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'noExterior')->textInput() ?>
                <?= $form->field($model, 'noInterior')->textInput() ?>
                <?= $form->field($model, 'colonia')->textInput() ?>
                <?= $form->field($model, 'codigoPostal')->textInput() ?>
                <?= $form->field($model, 'ciudad')->textInput() ?>
                <?= $form->field($model, 'estado')->textInput() ?>
                <?= $form->field($model, 'pais')->textInput() ?>
                <div class="form-group"></div>
                <div class="form-group">
                    <?= Html::submitButton('Ingresar Pago', ['class' => 'btn btn-primary', 'name' => 'direccion-button']) ?>
                </div>
        </div>    
    </div>
    <?php ActiveForm::end(); ?>
    <?php if (count($direcciones)>0): ?>
          <h1 class="titulo">Direcciones</h1>

          <table class="table table-bordered table-striped table-hover">
            <tr>
           <th>Calle</th>
           <th>Colonia</th>
           <th>Ciudad</th>
           <th>Pais</th>
           <th>Codigo Postal</th>
           <th>Seleccionar Direccion</th>
          </tr>
        <?php foreach($direcciones as $row): ?>
            <tr>
              <td><?= $row->calle ?> </td>
              <td><?= $row->colonia ?></td>
              <td><?= $row->ciudad?></td>
              <td><?= $row->pais?></td>
              <td><?= $row->codigoPostal?></td>
              <td><?= Html::beginForm(Url::toRoute("ventas/usardireccion"), "POST") ?>
                                    <input type="hidden" name="id" value="<?= $row->id ?>">
                                    <button type="submit" class="btn btn-primary">Seleccionar</button>
                                    <?= Html::endForm() ?></td>
    </tr>
    <?php endforeach ?>
    </table>
    <?php endif; ?>
</div>

views/ventas/pago.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Pago';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pago-register">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Por favor ingrese sus datos de pago:</p>
    
    <div>
        <div>
            <?php $form = ActiveForm::begin([
                                    'id' => 'form-pago',
                                    'method' => 'post',
                                    'action' => ['ventas/agregarpago'],
                                ]); ?>

                <div class="prendaContainer">
                    <div class="labelPrenda">Subtotal:</div>
                    <?= Html::input('text', 'total', number_format($model->subtotal,2,".",",") ,['readonly' => true]) ?>
                </div>
                <div class="prendaContainer">
                    <div class="labelPrenda">Iva:</div>
                    <?= Html::input('text', 'total', number_format($model->iva,2,".",","),['readonly' => true]) ?>
                </div>
                <div class="prendaContainer">
                    <div class="labelPrenda">Total:</div>
                    <?= Html::input('text', 'total', number_format($model->total,2,".",","),['readonly' => true]) ?>
                </div>

                <?= $form->field($model, 'idTipoPago')->dropDownList(['1' => 'Una sola exhibición', '2'=>'Crédito']); ?>

                <div class="form-group"></div>
                <div class="form-group pago-container">
                    <?= Html::submitButton('Pagar', ['class' => 'btn btn-primary', 'name' => 'pago-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>

</div>