controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\PerfilOpcion;
use app\models\Opcion;
use app\models\Prenda;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\User;
use yii\jui\AutoComplete;
use yii\web\JsExpression;
use yii\helpers\Url;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */

    public function actionRequest(){

    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $data = Prenda::find()
        ->select(['nombre as value', 'nombre as  label','id as id'])
        ->asArray()
        ->all();
        $prendas = Prenda::obtenerPrendasSite();
        $urlbase = Url::base(true);
        $prendasTemporada = Prenda::obtenerPrendasPorTemporadas();
        Yii::$app->session['prenda'] = $data;
        return $this->render('index',['model'=>$data, 'data'=>$data, 'prendas'=>$prendas, 'urlbase'=>$urlbase, 'prendasTemporada'=>$prendasTemporada]);
    }

    public function actionBuscar()
    {
        if(Yii::$app->request->post()){
            $campoBusqueda = Html::encode($_POST["Prenda"]);

            $prendas = Prenda::obtenerPrendasBuscador($campoBusqueda);
            if($prendas!=null){
                if($campoBusqueda!=""){
                    $urlbase=Url::base(true);
                    return $this->render('buscar',['model'=>$prendas,'msg'=>"", 'urlbase'=>$urlbase]);
                }else{
                    $msg="No se ingresaron datos para buscar.";
                    return $this->render('buscar',['model'=>'','msg'=>$msg,'urlbase'=>'']);
                }
            }else{
                $msg="No hay resultados en la búsqueda.";
                return $this->render('buscar',['model'=>'','msg'=>$msg,'urlbase'=>'']);
            }      
        }
        
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $modelPerfilOpcion = new PerfilOpcion();
        $modelOpcion = new Opcion();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $user = $model->getUser();
            $opcionesPorPerfil = $modelPerfilOpcion->obtenerOpcionesPorPerfil($user->idPerfil);
            $listOpcionesPorPerfil = ArrayHelper::map($opcionesPorPerfil, 'idOpcion', 'idOpcion');
            $opciones = $modelOpcion->obtenerOpcionesPorIds($listOpcionesPorPerfil);
            $listOpciones = ArrayHelper::map($opciones, 'descripcion', 'url');
            Yii::$app->session['idUsuario'] = $user->id;
            Yii::$app->session['emailUsuario'] = $user->email;
            Yii::$app->session['opciones'] = $listOpciones;
            $prendasTemporada = Prenda::obtenerPrendasPorTemporadas();
            $prendas = Prenda::obtenerPrendasSite();
            return $this->render('index', [
                'model' => $model,
                'prendasTemporada'=>$prendasTemporada,
                'prendas'=>$prendas
            ]);
        }
        
        return $this->render('login', [
            'model' => $model, 
            'msg' => "",
            'tipo' => 0,
            'prendasTemporada'=>''
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionIngresar()
    {
        return $this->render('ingresarcontrasenia',['msg'=>"",'tipo'=>0]);
    }

    public function actionCambiar(){
        if(Yii::$app->request->post()){
            $email = Html::encode($_POST["email"]);
            $password = Html::encode($_POST["password"]);
            $user = User::findByEmail($email);
            if($user!=null){
                if(User::cambiarContraseña($user,$password) !==false){
                    $msg="Te has registrado correctamente, inicia sesión.";
                    $model = new LoginForm();
                    return $this->render('login',['model'=>$model,'msg'=>$msg,'tipo'=>1]);
                }else{
                    $msg="Correo no registrado, verifique sus datos.";
                    $model = new LoginForm(); 
                    return $this->render('ingresarcontrasenia',['msg'=>$msg,'tipo'=>1]);
                }
            }else{
                $msg="El correo ingresado no es correcto, verifique sus datos.";
                $model = new LoginForm(); 
                return $this->render('ingresarcontrasenia',['msg'=>$msg,'tipo'=>1]);
            }      
        }
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'RopaLinda';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <div class="jumbotron">
        <img class="logoAbout" src="images/logo2.jpeg" />
        <p>Empresa 100% sinaloense dedicada al diseño, producción, venta y distribución de ropa para hombres y mujeres desde marzo del 2009, ofreciendo producto y servicio de alta calidad a un precio justo.</p>
    </div>
    <div class="jumbotron">
        <div class="aboutTitle">Misión</div>
        <p>Ofrecer el mejor producto y servicio que tengan calidad y valor para el cliente.</p>
    </div>
    <div class="jumbotron">
        <div class="aboutTitle">Visión</div>
        <p>Ser la marca de ropa preferida que vista a todo el mundo por su calidad y comodidad.</p>
    </div>
    <div class="jumbotron">
        <div class="aboutTitle">Valores</div>
        <p>Responsabilidad social</p>
        <p>Transparencia y Honestidad</p>
        <p>Respeto</p>
        <p>Equidad</p>
        <p>Empatía</p>
    </div>
    <style type="text/css">
        .jumbotron{
            background-color: #000;
            color: white;
        }
    </style>
    
</div>

views/site/buscar.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Búsqueda';
$this->params['breadcrumbs'][] = $this->title;
?> 
<div class="site-buscar">
    <br>
    <br>
    <?php if($model!=null):?>
        <table class="table table-bordered text-center">
            <tr>
                <th></th>
                <th style="text-align:center">Nombre</th>
                <th style="text-align:center">Precio</th>
                <th style="text-align:center">Descripcion</th>
                <th></th>
            </tr>
            <?php foreach($model as $row): ?>
            <?php $urlfinal = $urlbase.$row->urlImagen; ?>
            <tr> 
                <td style="text-align:center"><br/><p><img src=<?=$urlfinal ?> alt="Imagen de la Prenda" style="width:100px;height:100px;" ></p></td>
                <td><?= $row->nombre  ?></td>
                <td><?= $row->precio ?></td>
                <td><?= $row->descripcion ?></td>
                <td style="text-align:center"><a href="<?= Url::toRoute(["prendas/mostrarprenda", "id" => $row->id]) ?>" class="btn btn-info">Mostrar</a></td>
            </tr>
            <?php endforeach ?>
        </table>
    <?php else: ?>
    <div class="alert alert-danger">
        <h4 ><?= $msg ?></h4>
    </div>
    <?php endif; ?>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contáctanos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Gracias por contactarnos. Te responderemos los más pronto posible.
        </div>
        
    <?php else: ?>

        <p>
        Si tiene consultas comerciales u otras preguntas, complete el siguiente formulario para contactarnos. Gracias.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Enviar', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        El error anterior ocurrió mientras el servidor web estaba procesando su solicitud.
    </p>
    <p>
        Póngase en contacto con nosotros si cree que se trata de un error del servidor. Gracias.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\jui\AutoComplete;
use yii\web\JsExpression;

/* @var $this yii\web\View */

$this->title = 'Inicio';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index mainContainer">
  <?php 
    $images=['<img src="/images/autumn-winter_season.jpg"/>'];
    echo yii\bootstrap\Carousel::widget(['items'=>$images]);
  ?>

  <div class="content-container">
    <div class="sub-header">Ofertas de temporada</div>
    <section class="items-list">
      <?php foreach($prendasTemporada as $row): ?>
        <?php $urlfinal = Url::base(true).$row->urlImagen ?>
        <a href="<?= Url::toRoute(["prendas/mostrarprenda", "id" => $row->id]) ?>" class="item">
          <figure class="item-image">
            <img src=<?=$urlfinal ?> alt="Imagen de la Prenda">
          </figure>
          <span class="item-overlay">
            <div class="item-info">
              <span class="item-name"><?= $row->nombre ?></span>
              <span class="item-price">$<?= $row->precio ?></span>
            </div>
          </span>
        </a>
      <?php endforeach ?>
    </section>
  </div>
  <div class="content-container">
    <div class="sub-header">Todos los productos</div>
    <section class="items-list">
      <?php foreach($prendas as $row): ?>
        <?php $urlfinal = Url::base(true).$row->urlImagen ?>
        <a href="<?= Url::toRoute(["prendas/mostrarprenda", "id" => $row->id]) ?>" class="item">
          <figure class="item-image">
            <img src=<?=$urlfinal ?> alt="Imagen de la Prenda">
          </figure>
          <span class="item-overlay">
            <div class="item-info">
              <span class="item-name"><?= $row->nombre ?></span>
              <span class="item-price">$<?= $row->precio ?></span>
            </div>
          </span>
        </a>
      <?php endforeach ?>
    </section>
  </div>
</div>

views/site/ingresarcontrasenia.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Contraseña';
?> 
<div class="site-cambiarcontrasenia">
    <h2>Estás a un paso de ser nuestro cliente!</h2>
    <h3>Por favor ingresa el correo registrado y una contraseña.</h3>
    <?php if($tipo==1): ?>
    <div class="alert alert-danger">
        <?= nl2br(Html::encode($msg)) ?>
    </div>
    <?php endif; ?>
    <?= Html::beginForm(Url::toRoute("site/cambiar"), "POST") ?>
        <div class="form-group">
        Correo: <input type="text" name="email" required size="30" maxlength="30">
        Contraseña: <input type="password" name="password" maxlength="30" size="30" required>

        <?= Html::submitButton('Aceptar', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>

        </div>
    <?= Html::endForm() ?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Iniciar Sesión';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if($tipo==1): ?>
        <div class="alert alert-success">
            <?= nl2br(Html::encode($msg)) ?>
        </div>
    <?php endif; ?>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'email')->textInput() ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Iniciar Sesión', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>