models/Prenda.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use app\models\entities\EntityPrendas;

class Prenda extends \yii\db\ActiveRecord {


    public static function tableName()
    {
        return EntityPrendas::tableName();
    }
    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['nombre'], 'required', 'message' => 'El nombre no debe ser vacío.'],
            [['descripcion'], 'required', 'message' => 'La descripción no debe ser vacía.'],
            [['idCategoria'], 'required', 'message' => 'La categoría no debe ser vacía.'],
            [['idSubCategoria'], 'required', 'message' => 'La subCategoría no debe ser vacía.'],
            [['idTemporada'], 'required', 'message' => 'La temporada no debe ser vacía.'],
            [['urlImagen'], 'required', 'message' => 'Debe seleccionar una imagen para la prenda.'],
            [['urlImagenMiniatura'], 'required', 'message' => 'Debe seleccionar una imagen miniatura para la prenda.']
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'nombre' => 'Ingrese nombre de la prenda',
            'descripcion' => 'Ingrese descripcion',
            'tipoPrenda' => 'Selecciones tipo de Prenda',
            'urlImagen' => 'Seleccione imagen de prenda',
            'urlImagenMiniatura' => 'Seleccione imagen miniatura de prenda',
            'idCategoria' => 'Seleccione categoria',
            'idTemporada' => 'Seleccione temporada',
            'idSubCategoria'=>'Seleccione sub categoria'
        ];
    }

    public static function obtenerPrendas()
    {
        return static::find()->all();
    }

    public static function obtenerPrendasSite()
    {
        return static::find()->Where(['>', 'precio', 0.0])->all();
    }

    public static function obtenerPrendasPorTemporadas()
    {
        return static::find()->where(['in', 'idTemporada', 1])->all();
    }

    public static function obtenerPrendasPorIds($prendas)
    {
        return static::find()
            ->where(['in', 'id', $prendas])
            ->all();
    }

    public static function obtenerPrendasBuscador($search){
        return static::find()->where(['LIKE','nombre',$search])->orWhere(['LIKE','descripcion',[$search]])->all();        
    }

    public static function guardarPrenda($prenda,$tipoPrenda){
        $fechaAlta = date("Y-m-d");
        $prenda->tipoPrenda = $tipoPrenda;
        $prenda->fechaAlta = $fechaAlta;
        $prenda->urlImagenMiniatura = '';
        return $prenda->save(false);
    }

    public function borrarPrenda($idPrenda){
        static::deleteAll(['id'=>$idPrenda]);
    }

    public  function guardarPrendaPersonalizada($idPrenda,$totalComponentes){
        $prendaAPersonalizar = static::findOne($idPrenda);
        $fechaAlta = date("Y-m-d");
        $prendaNueva = new Prenda();
        $prendaNueva->tipoPrenda = "PERSONALIZADA";
        $prendaNueva->fechaAlta = $fechaAlta;
        $prendaNueva->nombre = $prendaAPersonalizar->nombre;
        $prendaNueva->precio = $prendaAPersonalizar->precio + $totalComponentes;
        $prendaNueva->descripcion = $prendaAPersonalizar->descripcion;
        $prendaNueva->idTemporada = $prendaAPersonalizar->idTemporada;
        $prendaNueva->urlImagen = $prendaAPersonalizar->urlImagen;
        $prendaNueva->urlImagenMiniatura = '';
        $prendaNueva->idCategoria = $prendaAPersonalizar->idCategoria;
        $prendaNueva->idSubCategoria = $prendaAPersonalizar->idSubCategoria;
        $prendaNueva->save(false);
        return $prendaNueva;
    }

}

controllers/PrendasController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Prenda;
use app\models\Categoria;
use app\models\SubCategoria;
use app\models\Temporada;
use app\models\Componente;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use app\models\UploadForm;
use app\models\FormSearch;
use yii\web\UploadedFile;


class PrendasController extends Controller
{

    public function actionPrendas(){
        $prendas = Prenda::obtenerPrendas();
        $urlbase=Url::base(true);
        return $this->render('prendas',['model'=>$prendas,'urlbase'=>$urlbase, 'msg'=>"",'tipo'=>""]);
    }

    public function actionMostrardetalle(){
        if(Yii::$app->request->get("id")){
            $idPrenda = Html::encode($_GET["id"]);
            if((int)$idPrenda){
             $model = Prenda::findOne($idPrenda);
             Yii::$app->session['idPrenda'] = $idPrenda;
             $componentes = Componente::obtenerComponentesPrenda($idPrenda);
             $descripciontemporada= Temporada::findOne($model->idTemporada)->tipoTemporada;
             $descripcionCategoria = Categoria::findOne($model->idCategoria)->descripcion;
             $descripcionSubCategoria = SubCategoria::findOne($model->idSubCategoria)->descripcion;
             return $this->render('prenda',['model'=>$model,'temporada'=>$descripciontemporada
             ,'categoria'=>$descripcionCategoria,'subcategoria'=>$descripcionSubCategoria,'componentes'=>$componentes,
             'msg'=>'','tipo'=>'']);
            }
        }else{
             $prendas = Prenda::obtenerPrendas();
             return $this->render('prendas',['model'=>$prendas,'urlbase'=>Url::base(true),'msg'=>"",'tipo'=>'']);
        }
        
    }
    public function actionMostrarprenda(){
        if(Yii::$app->request->get("id")){
            $idPrenda = Html::encode($_GET["id"]);
            if((int)$idPrenda){
             $model = Prenda::findOne($idPrenda);
             Yii::$app->session['idPrenda'] = $idPrenda;
             $componentes = Componente::obtenerComponentesPrenda($idPrenda);
             $descripciontemporada= Temporada::findOne($model->idTemporada)->tipoTemporada;
             $descripcionCategoria = Categoria::findOne($model->idCategoria)->descripcion;
             $descripcionSubCategoria = SubCategoria::findOne($model->idSubCategoria)->descripcion;
             return $this->render('prendaPersonalizar',['model'=>$model,
                                                        'temporada'=>$descripciontemporada,
                                                        'categoria'=>$descripcionCategoria,
                                                        'subcategoria'=>$descripcionSubCategoria,
                                                        'componentes'=>$componentes,
                                                        'tipo'=>'',
                                                        'msg'=>""]);
            }
        }else{
             $prendas = Prenda::obtenerPrendas();
             return $this->render('buscar',['model'=>$prendas,'urlbase'=>Url::base(true),'msg'=>""]);
        }
    }

    public function actionAgregar(){
        $model = new Prenda();

        $categorias = Categoria::obtenerCategorias();
        $listCategorias=ArrayHelper::map($categorias,'id','descripcion');
        $subCategorias = SubCategoria::obtenerSubCategorias();
        $listSubCategorias = ArrayHelper::map($subCategorias,'id','descripcion');
        $temporadas = Temporada::obtenerTemporadas();
        $listTemporadas=ArrayHelper::map($temporadas,'id','tipoTemporada');

        return $this->render('agregarPrenda',['model'=>$model,
                                                'listCategorias'=>$listCategorias,
                                                'listSubCategorias'=>$listSubCategorias,
                                                'listTemporadas'=>$listTemporadas, 
                                                'msg'=>"",'cargada'=>"NO",
                                                'im1'=>""]);
    }

    public function actionSaveprenda(){
        $model = new Prenda();

        if (Yii::$app->request->post()) {
            
            $model->urlImagen = Html::encode($_FILES["imagenCompleta"]['name']);

            $file1 = $_FILES['imagenCompleta']['name'];

            $expensions= array("jpeg","jpg","png");
    
            if(!is_dir("../web/files/clothes/")) {
                mkdir("../web/files/clothes/", 0777);
            }
                
            $urlNueva = "../web/files/clothes/".$file1;

            move_uploaded_file($_FILES['imagenCompleta']['tmp_name'],$urlNueva);

            $categorias = Categoria::obtenerCategorias();
            $listCategorias=ArrayHelper::map($categorias,'id','descripcion');
            $subCategorias = SubCategoria::obtenerSubCategorias();
            $listSubCategorias = ArrayHelper::map($subCategorias,'id','descripcion');
            $temporadas = Temporada::obtenerTemporadas();
            $listTemporadas=ArrayHelper::map($temporadas,'id','tipoTemporada');

            $im1 = "/files/clothes/".$file1;
            return $this->render('agregarPrenda',['model'=>$model,
                                                'listCategorias'=>$listCategorias,
                                                'listSubCategorias'=>$listSubCategorias,
                                                'listTemporadas'=>$listTemporadas, 
                                                'msg'=>"",'cargada'=>"SI",
                                                'im1'=>$im1]);
        }elseif(Yii::$app->request->get()){
            return $this->render('agregarPrenda',['model'=>$model,
                                                'listCategorias'=>'',
                                                'listSubCategorias'=>'',
                                                'listTemporadas'=>'', 
                                                'msg'=>"",'cargada'=>"NO",
                                                'im1'=>'']);
        }
    }

    public function actionGuardarprenda(){
        $model = new Prenda();
        if ($model->load(Yii::$app->request->post())){

            if(Prenda::guardarPrenda($model, $_POST['Prenda']['tipoPrenda']) !==false){
                $prendas = Prenda::obtenerPrendas();
                return $this->render('prendas',['model'=>$prendas,
                                                'urlbase'=>Url::base(true), 
                                                'msg'=>"Prenda guardada correctamente.",
                                                'tipo'=>1]);
            }else{
                $categorias = Categoria::obtenerCategorias();
                $listCategorias=ArrayHelper::map($categorias,'id','descripcion');
                $subCategorias = SubCategoria::obtenerSubCategorias();
                $listSubCategorias = ArrayHelper::map($subCategorias,'id','descripcion');
                $temporadas = Temporada::obtenerTemporadas();
                $listTemporadas=ArrayHelper::map($temporadas,'id','tipoTemporada');
                $msg="Ocurrió un problema al guardar la prenda, vuelva a intentarlo.";
                $cargada = "NO";

                return $this->render('agregarPrenda',['model'=>$model,
                                                'listCategorias'=>$listCategorias,
                                                'listSubCategorias'=>$listSubCategorias,
                                                'listTemporadas'=>$listTemporadas, 
                                                'msg'=>"Ocurrió un problema al guardar la prenda, vuelva a intentarlo.",
                                                'cargada'=>"NO",
                                                'im1'=>""]);    
            }
        }
    }

    public function actionAgregarcomponente(){
        $model = new Componente();
        if(Yii::$app->request->get("id")){
            $idPrenda = Html::encode($_GET["id"]);
            if((int)$idPrenda){
                return $this->render('agregarComponente', ['model'=>$model, 
                                                           'msg'=>"",
                                                           'id'=>$idPrenda,
                                                           'cargada'=>'NO',
                                                           'im1'=>""]);
            }else{
                $model = Prenda::findOne($idPrenda);
                $descripciontemporada= Temporada::findOne($model->idTemporada)->tipoTemporada;
                $descripcionCategoria = Categoria::findOne($model->idCategoria)->descripcion;
                $descripcionSubCategoria = SubCategoria::findOne($model->idSubCategoria)->descripcion;
                return $this->render('prenda',['model'=>$model,'temporada'=>$descripciontemporada
                ,'categoria'=>$descripcionCategoria,'subcategoria'=>$descripcionSubCategoria,
                'msg'=>'','tio'=>'']);
            }
        }
    }

    public function actionSavecomponente(){
        $model = new Componente();

        if (Yii::$app->request->post()) {
            
            $model->urlImagen = Html::encode($_FILES["componenteCompleto"]['name']);

            $file1 = $_FILES['componenteCompleto']['name'];

            $expensions= array("jpeg","jpg","png");
    
            if(!is_dir("../web/files/components/")) {
                mkdir("../web/files/components/", 0777);
            }
                
            $urlNueva = "../web/files/components/".$file1;

            move_uploaded_file($_FILES['componenteCompleto']['tmp_name'],$urlNueva);

            $im1 = "/files/components/".$file1;
            $idPrenda = Yii::$app->session['idPrenda'];
            return $this->render('agregarComponente',['model'=>$model,

views/prendas/agregarComponente.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Agregar Componente';
$this->params['breadcrumbs'][] = $this->title;
?>
<h4 ><?= $msg ?></h4>
<div class="componentes-agregar">
    <h1 class="titulo">Nuevo Componente</h1>
    <div class="row">
        <div class="col-lg-5">
            <?php if ($cargada=="NO"): ?>
                
                <?php $form1 = ActiveForm::begin([
                        'id' => 'componente-2',
                        'method' => 'post',
                        'action' => ['prendas/savecomponente'],
                        'options' => ['enctype' => 'multipart/form-data'],]); ?>
                    <?= $form1->field($model, 'urlImagen')->fileInput(['multiple' => true,
                    'id' => 'imgInpCC', 'name'=>'componenteCompleto']) ?>
                    <img id="precargaComponenteC" src="<?= $im1 ?>" style="width:200px;height:200px;"/> 
                    <div class="form-group">
                        <?= Html::submitButton('Continuar', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>
                <?php ActiveForm::end();?>
            <?php else: ?>
                <?php $form = ActiveForm::begin([
                    'id' => 'componente',
                    'method' => 'post',
                    'action' => ['prendas/guardarcomponente'],]); ?>
                    <?=$form->field($model, 'urlImagen')->hiddenInput(['value'=> $im1])->label(false); ?>
                    <h4>Imagen componente</h4>
                    <img id="precargaComponenteC" src="<?= $im1 ?>" style="width:200px;height:200px;"/>
                    <?= $form->field($model, 'nombre')->textInput(['autofocus' => true]) ?>
                    <?= $form->field($model, 'descripcion')->textarea(['rows' => 6]) ?>
                    <?= $form->field($model,'idPrenda')->hiddenInput(['options' => ['idPrenda'=> $id] ])->label(false);?>
                    <div class="form-group">
                        <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>
                <?php ActiveForm::end(); ?>
                <?php $form2 = ActiveForm::begin([
                        'id' => 'componente-2',
                        'method' => 'get',
                        'action' => ['prendas/savecomponente'],]); ?>
                        <div class="form-group">
                            <?= Html::submitButton('Regresar', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                        </div>
                <?php ActiveForm::end(); ?>
            <?php endif; ?>
    </div>
</div>

views/prendas/agregarPrenda.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Agregar Prendas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="prendas-agregar"> 
<h1 class="titulo">Nueva Prenda Basica</h1>
<h4 ><?= $msg ?></h4>
<div class="row">
            <div class="col-lg-5">

                <?php if ($cargada=="NO"): ?>
                    
                    <?php $form1 = ActiveForm::begin([
                            'id' => 'prenda-2',
                            'method' => 'post',
                            'action' => ['prendas/saveprenda'],
                            'options' => ['enctype' => 'multipart/form-data'],]); ?>
                        <?= $form1->field($model, 'urlImagen')->fileInput(['multiple' => true,
                        'id' => 'imgInpC', 'name'=>'imagenCompleta']) ?>
                        <img id="precargaPrendaC" src="<?= $im1 ?>" style="width:200px;height:200px;"/> 
                        <div class="form-group">
                            <?= Html::submitButton('Continuar', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                        </div>
                    <?php ActiveForm::end();?>
                    
                <?php else: ?>
                    <?php $form = ActiveForm::begin([
                        'id' => 'prenda',
                        'method' => 'post',
                        'action' => ['prendas/guardarprenda'],]); ?>

                        <?=$form->field($model, 'urlImagen')->hiddenInput(['value'=> $im1])->label(false); ?>
                        <h4>Imagen prenda</h4>
                        <img id="precargaPrendaC" src="<?= $im1 ?>" style="width:200px;height:200px;"/>
                        <br>
                        <?= $form->field($model, 'nombre')->textInput() ?>
                        <?= $form->field($model,'tipoPrenda')->dropDownList(['BASICA' => 'BASICA', 'DISEÑADOR'=>'DISEÑADOR']); ?>
                        <?= $form->field($model, 'idCategoria')->dropDownList($listCategorias, ['prompt'=>'Selecciona Categoria'] );?>
                        <?= $form->field($model, 'idSubCategoria')->dropDownList($listSubCategorias, ['prompt'=>'Selecciona SubCategoria'] );?>
                        <?= $form->field($model, 'idTemporada')->dropDownList($listTemporadas, ['prompt'=>'Selecciona Temporada'] );?>
                        <?= $form->field($model, 'descripcion')->textarea(['rows' => 6]) ?>
                        
                        <div class="form-group">
                            <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                        </div>
                    <?php ActiveForm::end(); ?>
                    <?php $form2 = ActiveForm::begin([
                        'id' => 'prenda-2',
                        'method' => 'get',
                        'action' => ['prendas/saveprenda'],]); ?>
                        <div class="form-group">
                            <?= Html::submitButton('Regresar', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                        </div>
                    <?php ActiveForm::end(); ?>
                <?php endif; ?>
            </div>
        </div>
</div>

views/prendas/prenda.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Detalle Prenda';
$this->params['breadcrumbs'][] = $this->title;
?>
<h1 class="titulo">Prenda</h1>

<?php if($tipo==1): ?>
    <div class="alert alert-success">
        <h4><?= $msg ?></h4>
    </div>
<?php endif; ?>
<div class="infoContainer">
    <div class="imageContainer">
        <?php $urlfinal = Url::base(true).$model->urlImagen ?>
        <img src=<?=$urlfinal ?> alt="Imagen de la Prenda" />
    </div>
    <div class="infoPrenda">
        <div class="prendaContainer">
            <div class="labelPrenda">Nombre de la Prenda:</div>
            <?= Html::input('text', 'nombre', $model->nombre,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">Descripcion:</div>
            <?= Html::input('text', 'descripcion', $model->descripcion,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">Tipo de Prenda:</div>
            <?= Html::input('text', 'tipoPrenda', $model->tipoPrenda,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">Precio:</div>
            <?= Html::input('number', 'precio', $model->precio,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">Temporada:</div>
            <?= Html::input('text', 'temporada', $temporada,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">Categoria:</div>
            <?= Html::input('text', 'categoria', $categoria,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">SubCategoria:</div>
            <?= Html::input('text', 'subcategoria', $subcategoria,['readonly' => true,'size'=>'20','class'=>'form-control']) ?>
        </div>       
    </div>
</div>
<div class="buttonsContainer">
    <?= Html::beginForm(Url::toRoute(['prendas/prendas'])) ?>
       <button type="submit" class="btn btn-primary">Ir a Prendas</button>
    <?= Html::endForm() ?>
    <?= Html::beginForm(Url::toRoute(['prendas/agregarcomponente','id' => $model->id])) ?>
       <button type="submit" class="btn btn-primary">Agregar Componente</button>
    <?= Html::endForm() ?>
</div>
<?php if (count($componentes)>0): ?>
<h1 class="titulo">Componentes</h1>

   <table class="table table-bordered table-striped table-hover">
    <tr>
        <th class="tableCell baseWidth">Imagen</th>
        <th class="tableCell baseWidth">Nombre</th>
        <th class="tableCell baseWidth">Precio</th>
        <th class="tableCell description">Descripcion</th>
    </tr>
    <?php foreach($componentes as $row): ?>
    <tr>
        <?php $urlfinal = Url::base(true).$row->urlImagen ?>
        <td class="tableCell"><img src=<?=$urlfinal ?> alt="Imagen de la Prenda" style="width:100px;height:100px;" /></td>
        <td class="tableCell"><?= $row->nombre ?> </td>
        <td class="tableCell">$<?= $row->precio ?></td>
        <td class="tableCell"><?= $row->descripcion?></td>
    </tr>
    <?php endforeach ?>
</table>
<?php endif; ?>
   

views/prendas/prendaPersonalizar.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Prendas detalle';
$this->params['breadcrumbs'][] = $this->title;
?> 

<?php if($tipo==1): ?>
    <div class="alert alert-success">
        <h4 ><?= $msg ?></h4>
    </div>
<?php endif; ?>

<?php if($tipo==0 && $msg!=""): ?>
    <div class="alert alert-danger">
        <?= nl2br(Html::encode($msg)) ?>
    </div>
<?php endif; ?>

<div class="infoContainer">
    <div class="imageContainer">
        <?php $urlfinal = Url::base(true).$model->urlImagen ?>
        <img src=<?=$urlfinal ?> alt="Imagen de la Prenda" />
    </div>
    <div class="infoPrenda">
        <div class="prendaContainer">
            <div class="labelPrenda">Nombre de la Prenda:</div>
            <?= Html::input('text', 'nombre', $model->nombre,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">Descripcion:</div>
            <?= Html::input('text', 'descripcion', $model->descripcion,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">Tipo de Prenda:</div>
            <?= Html::input('text', 'tipoPrenda', $model->tipoPrenda,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">Precio:</div>
            <?= Html::input('number', 'precio', $model->precio,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">Temporada:</div>
            <?= Html::input('text', 'temporada', $temporada,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">Categoria:</div>
            <?= Html::input('text', 'categoria', $categoria,['readonly' => true, 'class'=>'form-control']) ?>
        </div>

        <div class="prendaContainer">
            <div class="labelPrenda">SubCategoria:</div>
            <?= Html::input('text', 'subcategoria', $subcategoria,['readonly' => true,'size'=>'20','class'=>'form-control']) ?>
        </div>       
    </div>
</div>

<?php $form = ActiveForm::begin(['method' => 'post', 'action' => ['ventas/agregarcarrito'],]); ?>
<div class="">
    <label for="sel1">Talla:</label>
    <select class="form-control" id="sel1" name="talla">
        <option>Chica</option>
        <option>Mediana</option>
        <option>Grande</option>
    </select>
    <label for="sel2">Color:</label>
    <select class="form-control" id="sel2" name="color">
        <option>Blanco</option>
        <option>Negro</option>
        <option>Azul marino</option>
        <option>Gris</option>
    </select>
    <div class="form-group">
        <label for="usr">Cantidad:</label>
        <input type="number" name="cantidad" min="1" class="form-control" id="usr" required="true">
    </div>
</div>

<div class="buttonsContainer buttonEnd">
    <input type="hidden" name="idprenda" value="<?= $model->id ?>">
    <button type="submit" class="btn btn-primary">Agregar al Carrito</button>
</div>


<?php if (count($componentes)>0): ?>
    <h1 class="titulo">Componentes</h1>

    <table class="table table-bordered table-striped table-hover">
        <tr>
            <th class="tableCell baseWidth">Imagen</th>
            <th class="tableCell baseWidth">Nombre</th>
            <th class="tableCell baseWidth">Precio</th>
            <th class="tableCell descripcion">Descripcion</th>
            <th class="tableCell baseWidth">Agregar</th>
        </tr>
        <?php $listaids = array(); ?>
        <?php foreach($componentes as $row): ?>
            <tr>
                <?php $urlfinal = Url::base(true).$row->urlImagenMiniatura ?>
                <td class="tableCell"><img src=<?=$urlfinal ?> alt="Imagen de la Prenda" style="width:100px;height:100px;" /></td>
                <td class="tableCell"><?= $row->nombre ?> </td>
                <td class="tableCell"><?= $row->precio ?></td>
                <td class="tableCell"><?= $row->descripcion?></td>
                <?php array_push($listaids,  $row->id); ?>
                <td class="tableCell"><input type="checkbox" name="idcomponente" value="<?= implode("|",$listaids); ?>" class="checkbox"></td>
            </tr>
        <?php endforeach ?>
    </table>
<?php endif; ?>
<?php ActiveForm::end(); ?>
   

views/prendas/prendas.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

$this->title = 'Prendas';
$this->params['breadcrumbs'][] = $this->title;
?> 
<h1 class="titulo">Prendas </h1>
<div class="divagregar">
    <?= Html::beginForm(Url::toRoute("prendas/agregar"), "POST") ?>
        <button type="submit" class="btn btn-primary">Agregar Prenda</button>
    <?= Html::endForm() ?>
</div>
<?php if($tipo==1): ?>
    <div class="alert alert-success">
        <h4><?= $msg ?></h4>
    </div>
<?php endif; ?>
<table class="table table-bordered table-striped table-hover">
    <tr>
        <th class="tableCell baseWidth">Imagen</th>
        <th class="tableCell baseWidth">Nombre</th>
        <th class="tableCell baseWidth">Tipo de Prenda</th>
        <th class="tableCell baseWidth">Precio</th>
        <th class="tableCell description">Descripcion</th>
        <th></th>
    </tr>
    <?php foreach($model as $row): ?>
    <?php $urlfinal = $urlbase.$row->urlImagen; ?>
    <tr> 
        <td class="tableCell"><img src=<?=$urlfinal ?> alt="Imagen de la Prenda" style="width:100px;height:100px;" ></td>
        <td class="tableCell"><?= $row->nombre  ?></td>
        <td class="tableCell"><?= $row->tipoPrenda ?> </td>
        <td class="tableCell">$<?= $row->precio ?></td>
        <td class="tableCell"><?= $row->descripcion ?></td>
        <td class="tableCell"><a href="<?= Url::toRoute(["prendas/mostrardetalle", "id" => $row->id]) ?>" class ="btn btn-primary">Mostrar Detalle</a></td>
    </tr>
    <?php endforeach ?>
</table>